apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-ratings-api-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: bookinfo
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-camel/developer-charts
    targetRevision: HEAD
    path: api-specification-pipeline
    helm:
      values: |
        domain: contract-first-camel
        system: bookinfo
        component: ratings
        groupid: com.redhat.bookinfo
        apicurioRegistry: registry-apicurio-registry.apps.cluster-m22mk.m22mk.sandbox2534.opentlc.com
        mockRegistry: microcks-microcks.apps.cluster-m22mk.m22mk.sandbox2534.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
